mp_default_homepage:
    pattern:  /theory
    defaults: { _controller: MPDefaultBundle:Default:index }
    requirements:
        _method:  GET
        
mp_default_about:
    pattern:  /about
    defaults: { _controller: MPDefaultBundle:Default:about }
    requirements:
        _method:  GET

mp_default_contact:
    pattern:  /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    requirements:
        _method:  GET
